# Generated by Django 6.0.5 on 2026-05-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('strategy_type', models.CharField(choices=[('moving_average', 'Moving Average Crossover'), ('rsi', 'RSI Strategy'), ('combined', 'Combined MA + RSI')], max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('position_size_percent', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('stop_loss_percent', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('take_profit_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='market_data.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
