# Generated by Django 6.0.5 on 2026-05-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('exchange', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='market_data.stock')),
            ],
            options={
                'ordering': ['timestamp'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'timestamp'), name='unique_stock_price_timestamp')],
            },
        ),
    ]
