# Generated by Django 6.0.5 on 2026-05-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number_of_trades', models.PositiveIntegerField(default=0)),
                ('win_loss_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='market_data.stock')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exit_reason', models.CharField(blank=True, max_length=40)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestresult')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
    ]
